// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Day1.Models;

[Table("Student")]
public partial class Student
{
    [Key]
    [Column("St_Id")]
    [DatabaseGenerated(DatabaseGeneratedOption.None)]
    public int ID { get; set; }

    [StringLength(50)]
    [Column("St_Fname")]
    public string name { get; set; }

    [Column("St_Age")]
    public int? age { get; set; }

    [Column("St_Address")]
    public string adddress { get; set; }

    [Column("Dept_Id")]
    public int? deptid { get; set; }

    [Column("St_super")]
    public int? supervisorId { get; set; }

    [ForeignKey("deptid")]
    [InverseProperty("Students")]
    public virtual Department dept { get; set; }

    [ForeignKey("supervisorId")]
    [InverseProperty("Subordinates")]
    public virtual Student Supervisor { get; set; }

    [InverseProperty("Supervisor")]
    public virtual ICollection<Student> Subordinates { get; set; } = new List<Student>();
}